import { CareerProps } from "../types/careers";

export const CAREERS: CareerProps[] = [
  {
    position: "Backend Golang Developer",
    company: "Pt. Affan Technology Indonesia (Parto.id)",
    logo: "/images/careers/parto-id.png",
    location: "Jambi, Indonesia 🇮🇩",
    location_type: "Onsite",
    type: "Internship",
    start_date: "2025-07",
    end_date: "2025-09",
    industry: "Marketplace B2B/B2G",
    link: "https://parto.id/",
    responsibilities: [
      "Developed and maintained backend services using Golang for Parto.id's internal attendance application.",
      "Implemented efficient data handling and secure API integrations to support daily attendance workflows.",
      "Collaborated with frontend and product teams to ensure smooth functionality and seamless user experience.",
    ],
    isShow: true,
  },
  {
    position: "Frontend Web Developer",
    company: "Pt. Eltran Indonesia",
    logo: "/images/careers/eltran-indonesia.png",
    location: "Bandung, Indonesia 🇮🇩",
    location_type: "Remote",
    type: "Internship",
    start_date: "2025-05",
    end_date: "2025-11",
    industry: "Engineering, Procurement & Construction (EPC)",
    link: "https://eltran.co.id/",
    responsibilities: [
      "Developed a responsive and interactive landing page using Next.js to promote company services and solutions.",
      "Ensured SEO optimization and fast performance by leveraging Next.js features such as static site generation.",
      "Collaborated with design and marketing teams to align web presence with brand identity.",
    ],
    isShow: true,
  },
  {
    position: "Head of Technology in the Research and Technology Division",
    company:
      "Himpunan Mahasiswa Sistem Informasi Universitas Jambi (HIMASI UNJA)",
    logo: "/images/careers/himasi-unja.jpeg",
    location: "Jambi, Indonesia 🇮🇩",
    location_type: "Onsite",
    type: "Part-time",
    start_date: "2024-12",
    end_date: null,
    industry: "school",
    link: "https://himasi.unja.ac.id/",
    responsibilities: [
      "Led the development of an internal RFID-based attendance system for HIMASI UNJA.",
      "Managed the technical team and oversaw the implementation of hardware-software integration.",
      "Ensured the system was user-friendly, secure, and met the organization's operational needs.",
    ],
    isShow: true,
  },
  {
    position: "Mobile Development Cohort",
    company: "Bangkit Academy led by Google, Tokopedia, Gojek & Traveloka",
    logo: "/images/careers/bangkit.png",
    location: "Bandung, Indonesia 🇮🇩",
    location_type: "Remote",
    type: "Part-time",
    start_date: "2024-9",
    end_date: "2024-12",
    industry: "school",
    link: "https://himasi.unja.ac.id/",
    responsibilities: [
      "Mastered Android development using Kotlin, Jetpack Components, and modern tools like Room Database and DataStore for state and data management.",
      "Gained hands-on experience with ViewModel, RecyclerView, and Hilt for dependency injection to create robust and scalable mobile applications.",
      "Collaborated with a cross-functional team to develop a Company-Based Capstone Project, applying Agile methodologies and real-world problem-solving.",
      "Enhanced teamwork, problem-solving, and communication skills in a multicultural environment.",
    ],
    isShow: true,
  },
  {
    position: "Mobile Developer",
    company: "Pt. Amanah Karya Indonesia (Amanah Corp)",
    logo: "/images/careers/amanah-karya-indonesia.jpeg",
    location: "Depok, Indonesia 🇮🇩",
    location_type: "Remote",
    type: "Part-time",
    start_date: "2024-10",
    end_date: "2024-12",
    industry: "school",
    link: "https://amanahcorp.co.id/",
    responsibilities: [
      "Designed and developed a mobile application using Kotlin, incorporating Room Database, Hilt, and ViewModel for optimal performance and scalability.",
      "Implemented secure and user-friendly features tailored to the berbagi.link platform to improve user engagement and accessibility.",
      "Worked closely with PT Amanah Corp to ensure alignment with business objectives and deliver impactful, real-world solutions.",
      "Strengthened technical and soft skills, including problem-solving, teamwork, and communication, in a professional, multicultural setting.",
    ],
    isShow: true,
  },
];
