import type { Metadata } from "next";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";

import Layouts from "@/common/components/layouts";
import { soraSans } from "@/common/styles/fonts";
import ThemeProviderContext from "@/common/stores/theme";

export const metadata: Metadata = {
  title: "Satria Bahari | Personal Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={soraSans.className}>
        <NextTopLoader
          color="#05b6d3"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={true}
          easing="ease"
          speed={200}
          shadow="0 0 10px #05b6d3,0 0 5px #45c6c0"
        />
        <ThemeProviderContext>
          <Layouts>{children}</Layouts>
        </ThemeProviderContext>
      </body>
    </html>
  );
}
